import requests

def find_location(description):
    api_key = "YOUR_GOOGLE_MAPS_API_KEY"
    endpoint = "https://maps.googleapis.com/maps/api/place/findplacefromtext/json"
    
    params = {
        "input": description,
        "inputtype": "textquery",
        "fields": "formatted_address,name,geometry",
        "key": api_key
    }
    
    response = requests.get(endpoint, params=params)
    data = response.json()
    
    if data['status'] == 'OK':
        place = data['candidates'][0]  # Assuming we take the first result
        name = place['name']
        address = place['formatted_address']
        lat = place['geometry']['location']['lat']
        lng = place['geometry']['location']['lng']
        
        return name, address, lat, lng
    else:
        return None

if __name__ == "__main__":
    description = input("Enter a description: ")
    location = find_location(description)
    
    if location:
        name, address, lat, lng = location
        print(f"Name: {name}\nAddress: {address}\nLatitude: {lat}\nLongitude: {lng}")
    else:
        print("No matching location found.")
